%SYSTEMROOT%\SYSTEM32\REG.EXE DELETE "HKCU\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION" /v NobetterUltimateInternet.exe /f
%SYSTEMROOT%\SYSTEM32\REG.EXE DELETE "HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION" /v NobetterUltimateInternet.exe /f
%SYSTEMROOT%\SYSTEM32\REG.EXE DELETE "HKLM\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION" /v NobetterUltimateInternet.exe /f
EXIT